-- Drop tables if they exist (in correct order due to dependencies)
DROP TABLE IF EXISTS "path_user_enrollment" CASCADE;
DROP TABLE IF EXISTS "resource" CASCADE;
DROP TABLE IF EXISTS "activity" CASCADE;
DROP TABLE IF EXISTS "learning_path" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "profile" CASCADE;
DROP TABLE IF EXISTS "school_role" CASCADE;
DROP TABLE IF EXISTS "system_role" CASCADE;
DROP TABLE IF EXISTS "school" CASCADE;

-- ============================================
-- CORE TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS "system_role" (
    "id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(150) NOT NULL,
    "privileges" JSON,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "school_role" (
    "id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "privileges" JSON,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "profile" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "badges" JSON,
    "paths_completed" JSON,
    "paths_in_progress" JSON,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "school" (
    "id" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(150) NOT NULL,
    "status" VARCHAR(25) NOT NULL DEFAULT 'Active',
    "created_by" UUID,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id")
);

COMMENT ON COLUMN "school"."name" IS 'School Name';

CREATE TABLE IF NOT EXISTS "user" (
    "id" UUID NOT NULL,
    "name" VARCHAR(255),
    "mail" VARCHAR(150) NOT NULL UNIQUE,
    "status" VARCHAR(50) NOT NULL DEFAULT 'Active',
    "system_role_id" SMALLINT,
    "school_role_id" SMALLINT,
    "contact" JSON,
    "profile_id" INTEGER,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("id"),
    FOREIGN KEY("system_role_id") REFERENCES "system_role"("id") ON DELETE SET NULL,
    FOREIGN KEY("school_role_id") REFERENCES "school_role"("id") ON DELETE SET NULL,
    FOREIGN KEY("profile_id") REFERENCES "profile"("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "learning_path" (
    "id" UUID NOT NULL,
    "name" VARCHAR(150) NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "status" VARCHAR(50) NOT NULL DEFAULT 'Active',
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    "created_by" UUID NOT NULL,
    "school_id" SMALLINT,
    PRIMARY KEY("id"),
    FOREIGN KEY("created_by") REFERENCES "user"("id") ON DELETE CASCADE,
    FOREIGN KEY("school_id") REFERENCES "school"("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "activity" (
    "id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "step_number" SMALLINT,
    "path_id" UUID NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY("id"),
    FOREIGN KEY("path_id") REFERENCES "learning_path"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "resource" (
    "id" UUID NOT NULL,
    "activity_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "resource_data" JSON,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY("id"),
    FOREIGN KEY("activity_id") REFERENCES "activity"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "path_user_enrollment" (
    "path_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "enrolled_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "user_assign_id" UUID,
    "enrollment_info" JSON,
    "updated_at" TIMESTAMP,
    PRIMARY KEY("path_id", "user_id"),
    FOREIGN KEY("path_id") REFERENCES "learning_path"("id") ON DELETE CASCADE,
    FOREIGN KEY("user_id") REFERENCES "user"("id") ON DELETE CASCADE,
    FOREIGN KEY("user_assign_id") REFERENCES "user"("id") ON DELETE SET NULL
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX IF NOT EXISTS "idx_user_mail" ON "user"("mail");
CREATE INDEX IF NOT EXISTS "idx_user_status" ON "user"("status");
CREATE INDEX IF NOT EXISTS "idx_learning_path_school" ON "learning_path"("school_id");
CREATE INDEX IF NOT EXISTS "idx_learning_path_status" ON "learning_path"("status");
CREATE INDEX IF NOT EXISTS "idx_activity_path" ON "activity"("path_id");
CREATE INDEX IF NOT EXISTS "idx_resource_activity" ON "resource"("activity_id");
CREATE INDEX IF NOT EXISTS "idx_enrollment_user" ON "path_user_enrollment"("user_id");

-- Add foreign key to school after user table is created
ALTER TABLE "school"
ADD CONSTRAINT "fk_school_created_by"
FOREIGN KEY("created_by") REFERENCES "user"("id") ON DELETE SET NULL;